### ISSUE TITLE
Overriding the default behaviour of throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by gurappa** [OleksandrKucherenko/autoproxy#1]
We have a method in Activity which returns if activity has any dialog fragments are shown or not. For now of our case, app crashed, reason is Activity's predicate method returned false (as it must be finish()ing or onSaveInstance() is called) and so method throws UnsupportedOperationException(). 

Instead of throwing the exception, it could return the default boolean that I expect then I could handle (at least for this case it can be handled with default value).

Question is how/where can I change the code so that I can get the default value in case of predicate returning false and so I can avoid UnsupportedOperationException ?

**Comment by OleksandrKucherenko** [comment]
take a look on @AfterCall annotation. It allows to make a base class call and then decide which value to return.

**Comment by OleksandrKucherenko** [comment]
```
/** Does direct call independent to predicate result. */
    @AutoProxy.Yield(Returns.DIRECT)
    boolean dispatchDeepLink(@NonNull final Uri deepLink);
```

```
 public final boolean dispatchDeepLink(@NonNull final Uri deepLink) {
    if (!predicate( "dispatchDeepLink", deepLink )) {
      // @com.olku.annotations.AutoProxy.Yield("direct")
      // direct call, ignore predicate result
    }
    return this.inner.dispatchDeepLink(deepLink);
  }
```
