### ISSUE TITLE
Attempt to update Gradle resulted in AutoProxy to break.

### ISSUE THREAD

**Issue by gurappa** [OleksandrKucherenko/autoproxy#12]
We tried to upgrade gradle plugin version but AutoProxy is broken when we did that.
Do you have any clue why it does so ? Or can you help us raising gradle plugin version in your project where this lib is used and see if you face the problem. If you face, how you could solve it ?

**Comment by OleksandrKucherenko** [comment]
Do you have any details on how exactly it has broken? logs? exceptions?

**Comment by gurappa** [comment]
As discussed, I tried to build sample/ project and see if it builds successfully when gradle and android gradle plugin is raised. But project could not be setup. I have latest studio, 3.5.3. 

Here is the errror report:

> Configure project :
Is submodule: false

FAILURE: Build failed with an exception.

* What went wrong:
This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE FAILED in 939ms
This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.

**Comment by gurappa** [comment]
1. In sample project, when I add it as a maven dependency (instead of the module in the project), it works with latest gradle and plugin version. I added sample interface that is annotated with @AutoProxy and used generated Proxy_xxx in code...it works all good.
2. When I just copied the modules from my EasyPark project to the same sample project, then it does not work at all with any gradle version. I can share this project if you want to help out.

The source of AutoProxy module in EasyPark is diverged from what is in here in GitHub. For ex, you had added String THIS = "this"; in Returns.java.

I tried my best to fix this but could not. Not so straightforward to replace this one with some other solution. So help is really appreciated.

**Comment by OleksandrKucherenko** [comment]
did I correctly understand: it does not work when autoproxy included into the project as module with source code?

**Comment by gurappa** [comment]
Yes.
I copied the modules that you had created in EasyPark project to the sample project (just to see if EP project has any issues).
Failed to resolve reference to Proxy_GuruView.

@AutoProxy
interface GuruView {
    fun test()
}

**Comment by gurappa** [comment]
In EasyPark project with latest gradle and plugin, when I removed all the references to Proxy_***, build is successful.

**Comment by OleksandrKucherenko** [comment]
@gurappa check the latest version of the library... I add samples for Kotlin interface and abstract class. Check ver 0.3

**Comment by gurappa** [comment]
I will do that. But before that I need confirmation - EasyPark app has some custom changes done in this lib module. Are these changes now available in latest version so it would build sucessfully and also work as expected when I upgrade lib to ver 0.3 ??

**Comment by OleksandrKucherenko** [comment]
Just diff the code. If you have custom modifications, you are on your own with their support.... or Just make a PR into this repository, so I can merge them properly

**Comment by gurappa** [comment]
okay, I am trying for it now.
I will just copy all AutoProxy files from EasyPark to repo that is forked from your github. And I will create PR with the difference . Does that sounds okay ?

**Comment by OleksandrKucherenko** [comment]
Please try latest version 0.4

**Comment by OleksandrKucherenko** [comment]
https://github.com/OleksandrKucherenko/autoproxy/tree/fix-parking-area-compilation
